### ISSUE TITLE
Criar Userdata para subir instalar o Jenkins

### ISSUE THREAD

**Issue by enamba** [claranet-br/shield#2]
Criar o script em shell com os passos necessários para instalar o Jenkins com todos as libs para realizar os pipelines que temos criado

**Comment by mandalvesq** [comment]
Referencias:

http://www.scmgalaxy.com/tutorials/complete-guide-to-use-jenkins-cli-command-line/

https://d1.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf

https://docs.aws.amazon.com/aws-technical-content/latest/jenkins-on-aws/worker-nodes.html

**Comment by mandalvesq** [comment]
https://github.com/claranet-br/jenkins/pull/2/files
